.github/workflows/release-snapshot.yaml

- Adds `NPM_TOKEN` to the GitHub Action runner's `~/.npmrc` file so the `npm publish` step works
The snapshot publish workflow does not use the "changsets publish" functionality, which [automatically sets the npm token](https://github.com/changesets/action/blob/main/src/index.ts#L59) in the home directory's `.npmrc` file. This change will set the npm token, enabling the `npm publish` step to work for snapshots

fix: add NPM_TOKEN to ~/.npmrc to fix snapshot publishing

---

.github/workflows/release-snapshot.yaml
README.md
build.sbt
scripts/ci/configure-gpg.sh
scripts/ci/release-snapshot-sonatype.sh

- Adds a job to the `release_snapshot` GitHub Action workflow to release a snapshot to sonatype
- Adds a script to release a snapshot to sonatype
- Updates the README with information about releasing Sonatype snapshots

Scala snapshot releases

---

build.sbt
project/plugins.sbt

- Bumps `sbt-pgp` to `2.1.2`
- Only runs `sonatypeBundleRelease` if **not** releasing a snapshot. Otherwise, this step fails
- when releasing a snapshot, the `publishSigned` step uploads the artifacts to maven
- Removes the credential host override
These changes have been tested manually:
- [Successful GitHub Action run](https://github.com/guardian/apps-rendering-api-models/actions/runs/3376884189/jobs/5605145137)
- [Released snapshot in Sonatype](https://oss.sonatype.org/content/repositories/snapshots/com/gu/apps-rendering-api-models_2.12/0.0.0-2022-11-01.2-SNAPSHOT/)

Fix sonatype snapshot

---

models/scala/version.sbt
package.json
scripts/ci/update-version-sbt.sh

- We no longer use version.sbt to set the release version
- Instead, we set versions explicitly when calling sbt commands. The version is derived from git tags for Snapshot releases, or `package.json` for full releases

Do not set version in `version.sbt`

---

.github/workflows/release-snapshot.yaml

- Uses `actions/setup-node@v3` with a `registry-url` which is required for publishing ([docs](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#publish-to-npmjs-and-gpr-with-npm))
- Assigns the `NPM_TOKEN` repository secret to the `NODE_AUTH_TOKEN` environment variable when running the publish step
- A modified version of the changes were successfully tested in [this workflow run](https://github.com/guardian/apps-rendering-api-models/actions/runs/3363222522) associated with #8

fix: set npm registry and auth token environment variable

---

.github/workflows/changesets.yaml
README.md
scripts/ci/release-both.sh
scripts/ci/release-npm.sh
scripts/ci/release-sonatype.sh

- Adds a script to release to both `npm` and Sonatype when a "Release PR" is merged

Release to npm and sonatype

---

.changeset/soft-insects-dance.md
build.sbt

bumps the version on content api models to 17.4.0 for the new callout element type introduced here https://github.com/guardian/content-api-models/pull/216

Bump CAPI Models 17.4.0

---

.changeset/small-gifts-call.md
models/src/main/thrift/appsRendering.thrift

Part of the work required for https://github.com/guardian/dotcom-rendering/issues/6202. There are several different types of campaigns which MAPI understands. The current `campaigns` field only allows for one of these, callouts (or "participation campaigns"), to be passed through to AR. We would like access to report campaigns to handle special reports and special report alts. This adds support for these, and also for all the other types of campaigns for future use.
We can't alter the existing campaign types. MAPI and AR both depend on these models and are deployed independently, which means that they will briefly be on different versions when we roll these changes out. If we alter existing fields then AR won't understand the data being sent by MAPI during the brief window that they're …

More Campaign Types

---

scripts/ci/release-snapshot-sonatype.sh
scripts/ci/release-sonatype.sh

- sbt can indicate a snapshot release when it's a non-snapshot release
- for example, [this action run](https://github.com/guardian/apps-rendering-api-models/actions/runs/3427400645/jobs/5710855280#step:5:132) stopped short of publishing the package to Sonatype. It should have completed the publish, because `isSnapshot` was `true`. I expect this is because we are not using a `version.sbt` file

explicitly set isSnapshot for sonatype releases

---

build.sbt

- Conditionally adds release command `sonatypeBundleRelease` if **not** releasing a snapshot
- snapshot releases should not run this command as it will throw an error
Recent merges of "Release PRs" have published successfully to npm but not Sonatype. This is because the final step of `sonatypeBundleRelease` was not running. This change ensures that `sonatypeBundleRelease` runs when not releasing a snapshot change

Conditionally run the bundle release if not releasing a snapshot version

---

scripts/ci/release-sonatype.sh
scripts/ci/version-exists-sonatype.sh

- Adds a check to ensure the version being released does not already exist in Sonatype before trying to release. This is intended to prevent failed workflow runs in GitHub Actions

do not release to Sonatype if the version is already released

---

.changeset/curvy-experts-wait.md
models/src/main/thrift/appsRendering.thrift
package-lock.json

Adds two new properties to the Newsletter - these exist on the underlying data source (https://github.com/guardian/newsletters). For some new features, we'll to surface them in the frontend.
```
struct Newsletter {
1: required string identityName
2: required string name
3: required string theme
4: required string description
5: required string frequency
6: required string successDescription
7: optional string regionFocus
8: optional bool paused
}
```

add Newsletter.regionFocus and Newsletter.paused

---

.changeset/wild-badgers-confess.md
models/src/main/thrift/appsRendering.thrift

Adds `Europe` to editions enum as part of the work to create a new Europe edition.
This has been tested with related MAPI changes in CODE. (MAPI [PR](https://github.com/guardian/mobile-apps-api/pull/2126))

Add europe edition to ar thrift

---

.github/workflows/snyk.yml

The Dotcom team is now maintaining AR.
Paired with @ioannakok @Georges-GNM 
- Move Snyk to upload to Dotcom project

Move Snyk To Dotcom Project

---

.github/CODEOWNERS

- Removes `@guardian/apps-rendering` as a codeowner, as the apps rendering team has been merged into the WebX team
- Adds `@guardian/dotcom-platform` as a codeowner, as this team now maintains this repository

make `@guardian/dotcom-platform` codeowners

---

.changeset/brave-deers-grin.md
models/src/main/thrift/appsRendering.thrift

- Updates the field IDs for the `Contact` struct. These need to be unique, otherwise the model compilation fails (https://github.com/guardian/apps-rendering-api-models/actions/runs/4075726038/jobs/7022509922#step:5:77)
It would have been good if the automated checks caught this failure before attempting a release

Set field IDs for Contact struct

---

.github/workflows/test.yml
models/src/main/thrift/appsRendering.thrift

- adds the `test` workflow which compiles the model on a PR or push to `main`. The check should fail if the model does not compile, preventing the PR from being merged
There is currently no automated check to validate the thrift model. This resulted in a situation where we tried to release a version of the package which included an invalid model. The release failed, but we should have found out  about the issue earlier in the release lifecycle, before merging to `main`.
- [Example of the failing workflow](https://github.com/guardian/apps-rendering-api-models/actions/runs/4083658712/jobs/7039445252) on this branch when there is an error in the model

add GitHub workflow for testing whether a model is valid

---

.changeset/smart-meals-camp.md
models/src/main/thrift/appsRendering.thrift

This PR updates the `FormField` by adding a new field `hidden`
This change was tested locally in MAPI & AR through the published snapshot versions.

Add hidden field to FormField

---

.github/workflows/changesets.yaml

Possibly due to the trial of GitHub Enterprise, the changesets workflow is failing:
https://github.com/guardian/apps-rendering-api-models/actions/runs/5190780469/jobs/9357704131
...it no longer has the rights to push a tag:
```
/usr/bin/git push origin --tags
remote: Permission to guardian/apps-rendering-api-models.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/guardian/apps-rendering-api-models/': The requested URL returned error: 403
Error: Error: The process '/usr/bin/git' failed with exit code 128
Error: The process '/usr/bin/git' failed with exit code 128
```
@JamieB-gu pointed to [this chat](https://chat.google.com/room/AAAAag0I08g/ARIfdbu0axg) about the issue.
It seems we now need to explicitly grant workflows permissions in the yaml definition - our …

Attempt to fix changesets workflow

---

.github/workflows/changesets.yaml

Reverts guardian/apps-rendering-api-models#57 - it _was_ required:
https://github.com/guardian/apps-rendering-api-models/actions/runs/5200933865/jobs/9380367083#step:5:58
```
To https://github.com/guardian/apps-rendering-api-models
* [new branch]      HEAD -> changeset-release/main
{
"total_count": 0,
"incomplete_results": false,
"items": []
}
creating pull request
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
```

Revert "Is the `pull-requests: write` permission required here?"

---

build.sbt

Step on the road to Scala 3.
Changed the release command to use `releaseStepCommandAndRemaining`, as this is required for cross-compilation: https://github.com/xerial/sbt-sonatype#using-with-sbt-release-plugin

Started work to cross-compile to Scala 2.13

---

.github/workflows/release-snapshot.yaml

We were seeing [workflow failures](https://github.com/guardian/apps-rendering-api-models/actions/runs/6587440031/job/17897727511) indicating this might be the cause.

Give read permission to the `release-snapshot` workflow

---

.changeset/tidy-keys-ring.md
build.sbt
package-lock.json

This bumps the CAPI API model version to support some recent changes, namely the definition for the cartoon element and the `isMandatory` field for assets, in the app. This bump is required in order to complete the work to support the cartoon element in the Editions app. This is a companion pr for - https://github.com/guardian/dotcom-rendering/pull/9416
This has been published as a snapshot and can be checked in the apps rendering companion pr - https://github.com/guardian/dotcom-rendering/pull/9416

Bump CAPI version to 17.7.0

---

.changeset/cold-gifts-love.md
build.sbt

Bumps the CAPI and content atoms model versions on this project so that I can bump the commercial-shared version on MAPI.

Bump CAPI to 19.0.0

---

.changeset/kind-forks-wash.md
build.sbt

Bumps the version of CAPI models to include the new timeline element

Bump `contentApiModelsVersion`

---

.changeset/late-forks-confess.md
build.sbt

This PR bumps the `content-api-models` version to 25.0.0 in order to pull in new ListElement fields that will be used by Mini profiles format

Bump `contentApiModelsVersion` to 25.0.0

---

build.sbt

…after this error: https://github.com/guardian/apps-rendering-api-models/actions/runs/9677187765/job/26698313373#step:5:74
You can see that we were trying to download something that had a group ID of "apps-rendering-api-models" rather than "com.gu", so the download failed.
This was due to a misconfiguration in [the previous PR](https://github.com/guardian/apps-rendering-api-models/pull/90).

Move artifactProductionSettings into the right place

---

build.sbt

We spotted that this bit of configuration was missing from `build.sbt` - here it is serving the same purpose in `content-entity`: https://github.com/guardian/content-entity/blob/e3a6e8f28f44a44065fb001c0cf5e74361c35a90/build.sbt#L75C5-L75C36

Ensure that we do not try to publish typescript classes to maven central

---

README.md

Two changes:
* [![Release](https://github.com/guardian/apps-rendering-api-models/actions/workflows/release.yml/badge.svg)](https://github.com/guardian/apps-rendering-api-models/actions/workflows/release.yml) - a new 'Release' badge, linking straight to the Release workflow added in https://github.com/guardian/apps-rendering-api-models/pull/90 - a quick way to get to the place where you can make a release, and a status indicator showing if the last release failed.
* [![npm](https://img.shields.io/npm/v/@guardian/apps-rendering-api-models)](https://www.npmjs.com/package/@guardian/apps-rendering-api-models?activeTab=versions) - updating the NPM badge to link to the project on npmjs.com, always convenient when debugging the release process!

Update release badges on README.md

---

build.sbt

Model upgrade, so that we can bump the content api scala client version in MAPI

Update content api models to v27.0.0

---

build.sbt

* Brings in https://github.com/guardian/content-atom/releases/tag/v6.1.0.
* Brings in https://github.com/guardian/content-api-models/releases/tag/v31.0.0, which transiently brings in https://github.com/guardian/content-atom/releases/tag/v6.1.0.

Update content atom model
